import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCourseToChannelIndex1746000000000 implements MigrationInterface {
  name = 'AddCourseToChannelIndex1746000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop the old unique index on (tutor_id, learner_id) — name generated by TypeORM, found dynamically.
    const result: Array<{ indexname: string }> = await queryRunner.query(`
      SELECT indexname
      FROM pg_indexes
      WHERE tablename = 'chat_channel'
        AND indexdef LIKE 'CREATE UNIQUE INDEX%'
        AND indexdef LIKE '%tutor_id%'
        AND indexdef LIKE '%learner_id%'
        AND indexdef NOT LIKE '%course_id%'
      LIMIT 1
    `);
    if (result.length > 0) {
      await queryRunner.query(
        `DROP INDEX IF EXISTS "${result[0].indexname}"`,
      );
    }

    // New unique index scoped to (tutor_id, learner_id, course_id).
    // NULL course_id values are treated as distinct by PostgreSQL, allowing a
    // pre-booking channel (no course) alongside course-specific channels.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "IDX_chat_channel_tutor_learner_course"
      ON "chat_channel" ("tutor_id", "learner_id", "course_id")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_chat_channel_tutor_learner_course"`,
    );
    await queryRunner.query(`
      CREATE UNIQUE INDEX "IDX_chat_channel_tutor_learner"
      ON "chat_channel" ("tutor_id", "learner_id")
    `);
  }
}
