/**
 * Defines the possible lifecycle states of a TutorConnect booking.
 *
 * State transitions:
 *   PENDING_CONFIRMATION → CONFIRMED | REJECTED | EXPIRED
 *   CONFIRMED → COMPLETED | NO_SHOW | CANCELLED_BY_LEARNER | CANCELLED_BY_TUTOR | RESCHEDULED
 *
 * @author TutorConnect Team
 */
export enum BookingStatus {
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_LEARNER = 'CANCELLED_BY_LEARNER',
  CANCELLED_BY_TUTOR = 'CANCELLED_BY_TUTOR',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
  EXPIRED = 'EXPIRED',
}
